# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'GitbubAPI' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for GitbubAPI
	
	pod 'RxSwift'
  	pod 'RxCocoa'
  	pod 'Alamofire','~> 4.8.1'
  	pod 'AlamofireImage','~> 3.5.0'
  	pod 'SwiftyJSON'
  	pod 'SwiftLint'
    
  target 'GitbubAPITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'Quick'
    pod 'Nimble'
    pod 'RxTest'
  end

  target 'GitbubAPIUITests' do
    # Pods for testing
  end

end
